[package]
name = "rustls-ci-tests"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0 OR ISC OR MIT"
description = "Rustls CI tests"
publish = false

[dependencies]
rustls = { path = "../rustls" }
base64 = "0.21"
asn1 = "0.15"
